---
title: "Car Accident Severity Analysis Modeling"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## This is a team project. 

```{r}
library(dplyr)
```

```{r}
nc_new <- read.csv('nc_new.csv')
```

```{r}
nc_new <- nc_new[3:32]
```

```{r}
nc_new <- nc_new %>% filter(Wind_Direction != 'N/A') %>% filter(Weather_Condition != 'N/A')
```

```{r}
str(nc_new)
```

## Train and Test
```{r}
## 80% of the sample size
smp_size <- floor(0.80 * nrow(nc_new))
## set the seed to make your partition reproducible
set.seed(123)
train_ind <- sample(seq_len(nrow(nc_new)), size = smp_size)
train <- nc_new[train_ind, ]
test <- nc_new[-train_ind, ]
```

## Lasso
```{r}
install.packages("glmnet")
library(glmnet)
```

```{r}
x_train = model.matrix(Severity~Temperature.F.+Wind_Chill.F.+Humidity...+Pressure.in.+Wind_Direction+Wind_Speed.mph.+Junction+Station+Stop+Railway+Traffic_Signal+Traffic_Calming+Sunrise_Sunset+Side+Precipitation.in.+Weather_Condition+Amenity+Crossing+Give_Way, train)[,-1]

y_train = train %>%
  select(Severity) %>%
  unlist() %>%
  as.numeric()
```

```{r}
lasso_mod = glmnet(x_train,
                   y_train,
                   alpha = 1)
plot(lasso_mod)
```

```{r}
set.seed(12)
cv.out = cv.glmnet(x_train, y_train, alpha = 1)
plot(cv.out)
```

```{r}
bestlam = cv.out$lambda.min
bestlam
```

```{r}
lasso.treatment = glmnet(x_train, y_train, alpha = 1, lambda = bestlam)
coef(lasso.treatment)
```

## multinom Regression
```{r}
library(nnet)
```

```{r}
lm <- multinom(Severity~Temperature.F.+Wind_Chill.F.+Humidity...+Pressure.in.+Wind_Speed.mph.+Junction+Station+Stop+Railway+Traffic_Signal+Traffic_Calming+Sunrise_Sunset+Side+Precipitation.in.+Amenity+Crossing+Give_Way, data = train)
```

```{r}
summary(lm)
```

## P-Value
```{r}
z <- summary(lm)$coefficients/summary(lm)$standard.errors
```

```{r}
p <- (1-pnorm(abs(z), 0, 1)) * 2 
p
```

## Revised Model
```{r}
lm1 <- multinom(Severity~Temperature.F.+Wind_Chill.F.+Pressure.in.+Wind_Speed.mph.+Junction+Station+Stop+Railway+Traffic_Signal+Traffic_Calming+Sunrise_Sunset+Side+Precipitation.in.+Amenity+Crossing, data = train)
```

```{r}
summary(lm1)
```

```{r}
multi.glm = predict(lm1, newdata = test, type = 'class')
```

```{r}
response <- test$Severity
table(multi.glm, response)
mean(multi.glm == response)
```

## Decision Tree
```{r}
install.packages("rpart.plot")	
```

```{r}
library(rpart)
library(rpart.plot)
```

```{r}
tree = rpart(Severity~ Wind_Chill.F.+Side, data = train, method='class', control = rpart.control(cp = 0))
rpart.plot(tree)
```

```{r}
install.packages("tree")
```

```{r}
library(tree)
```

```{r}
tree1 = tree(Severity~Temperature.F.+Wind_Chill.F.+Humidity...+Pressure.in.+Wind_Direction+Wind_Speed.mph.+Junction+Station+Stop+Railway+Traffic_Signal+Traffic_Calming+Sunrise_Sunset+Side+Precipitation.in.+Weather_Condition+Amenity+Crossing+Give_Way, data = train, method = 'class')
plot(tree1)
text(tree1, label = 'yprob')
```


## Random Forest 
```{r}
install.packages("randomForest")
library(randomForest)
require(caTools)
```

```{r}
rf <- randomForest(factor(Severity)~Temperature.F.+Wind_Chill.F.+Humidity...+Pressure.in.+Wind_Direction+Wind_Speed.mph.+Junction+Station+Stop+Railway+Traffic_Signal+Traffic_Calming+Sunrise_Sunset+Side+Precipitation.in.+Weather_Condition+Amenity+Crossing+Give_Way, data = train, mtry = 4, nodesize = 5, ntree = 300)
```

```{r}
rf
```

```{r}
install.packages("MLmetrics")
```

```{r}
library(MLmetrics)
pred_car <- as.numeric(as.character(predict(rf, newdata = test)))
MSE(pred_car, test$Severity)
```

```{r}
response <- test$Severity
table(pred_car, response)
mean(pred_car == response)
```

```{r}
importance(rf)
varImpPlot(rf)
```

