---
title: "Car Accident Severity Analysis EDA"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## This is a team project.

```{r}
library(dplyr)
```
## Data Cleaning
```{r}
nc_data <- read.csv('nc_data.csv')
```

```{r}
nc_data <- nc_data %>% filter(Sunrise_Sunset!="")
```

```{r}
z <- sum(is.na(nc_data$Sunrise_Sunset))
z
```

```{r}
y <- sum(is.na(nc_data$Precipitation.in.))
y
```

```{r}
nc_data$Precipitation.in. <- ifelse(is.na(nc_data$Precipitation.in.), round(mean(nc_data$Precipitation.in., na.rm = TRUE), 0), nc_data$Precipitation.in.)
```

```{r}
x <- sum(is.na(nc_data$Visibility.mi.))
x
```

```{r}
a <- sum(is.na(nc_data$Temperature.F.))
a
```

```{r}
nc_data$Temperature.F. <- ifelse(is.na(nc_data$Temperature.F), round(mean(nc_data$Temperature.F, na.rm = TRUE), 0), nc_data$Temperature.F)
```

```{r}
b <- sum(is.na(nc_data$Temperature.F.))
b
```

```{r}
c <- sum(is.na(nc_data$Wind_Chill.F.))
c
```

```{r}
nc_data$Wind_Chill.F. <- ifelse(is.na(nc_data$Wind_Chill.F.), round(mean(nc_data$Wind_Chill.F., na.rm = TRUE), 0), nc_data$Wind_Chill.F.)
```

```{r}
d <- sum(is.na(nc_data$Wind_Chill.F.))
d
```

```{r}
e <- sum(is.na(nc_data$Humidity...))
e
```

```{r}
nc_data$Humidity... <- ifelse(is.na(nc_data$Humidity...), round(mean(nc_data$Humidity..., na.rm = TRUE), 0), nc_data$Humidity...)
```

```{r}
f <- sum(is.na(nc_data$Humidity...))
f
```

```{r}
g <- sum(is.na(nc_data$Pressure.in.))
g
```

```{r}
nc_data$Pressure.in. <- ifelse(is.na(nc_data$Pressure.in.), round(mean(nc_data$Pressure.in., na.rm = TRUE), 0), nc_data$Pressure.in.)
```

```{r}
h <- sum(is.na(nc_data$Pressure.in.))
h
```

```{r}
i <- sum(is.na(nc_data$Visibility.mi.))
i
```

```{r}
nc_data$Visibility.mi. <- ifelse(is.na(nc_data$Visibility.mi.), round(mean(nc_data$Visibility.mi., na.rm = TRUE), 0), nc_data$Visibility.mi.)
```

```{r}
j <- sum(is.na(nc_data$Visibility.mi.))
j
```

```{r}
k <- sum(is.na(nc_data$Wind_Direction))
k
```

```{r}
unique(nc_data$Wind_Direction)
```

```{r}
E <- c("E", "East")
W <- c("W", "West")
S <- c("S", "South")
N <- c("N", "North")
NW <- c("NNW", "NW", "WNW")
NE <- c("NE", "ENE", "NNE")
SW <- c("SW", "SSW", "WSW")
SE <- c("SE", "SSE", "ESE")
Calm <- c("CALM", "Calm", "Variable", "VAR")
```

```{r}
nc_data$Wind_Direction = sapply(as.vector(nc_data$Wind_Direction), function(x) if(x %in% E) "E" else x )
nc_data$Wind_Direction = sapply(as.vector(nc_data$Wind_Direction), function(x) if(x %in% W) "W" else x )
nc_data$Wind_Direction = sapply(as.vector(nc_data$Wind_Direction), function(x) if(x %in% S) "S" else x )
nc_data$Wind_Direction = sapply(as.vector(nc_data$Wind_Direction), function(x) if(x %in% N) "N" else x )
nc_data$Wind_Direction = sapply(as.vector(nc_data$Wind_Direction), function(x) if(x %in% NW) "NW" else x )
nc_data$Wind_Direction = sapply(as.vector(nc_data$Wind_Direction), function(x) if(x %in% NE) "NE" else x )
nc_data$Wind_Direction = sapply(as.vector(nc_data$Wind_Direction), function(x) if(x %in% SW) "SW" else x )
nc_data$Wind_Direction = sapply(as.vector(nc_data$Wind_Direction), function(x) if(x %in% SE) "SE" else x )
nc_data$Wind_Direction = sapply(as.vector(nc_data$Wind_Direction), function(x) if(x %in% Calm) "Calm" else x )
```

```{r}
nc_data$Wind_Direction = sapply(as.vector(nc_data$Wind_Direction), function(x) if(x %in% c("")) "N/A" else x )
```

```{r}
unique(nc_data$Wind_Direction)
```

```{r}
l <- sum(is.na(nc_data$Wind_Speed.mph.))
l
```

```{r}
nc_data$Wind_Speed.mph. <- ifelse(is.na(nc_data$Wind_Speed.mph.), round(mean(nc_data$Wind_Speed.mph., na.rm = TRUE), 0), nc_data$Wind_Speed.mph.)
```

```{r}
m <- sum(is.na(nc_data$Wind_Speed.mph.))
m
```

```{r}
light_condition = c("Light Rain", "Drizzle", "Mist", "Heavy Drizzle", "Light Ice Pellets", "Light Thunderstorms and Rain", "Light Rain / Windy", "Light Freezing Rain / Windy", "Widespread Dust", "Light Drizzle", "Light Snow", "Cloudy", "N/A Precipitation", "Overcast", "Partly Cloudy", "Mostly Cloudy", "Clear", "Fair", "Cloudy / Windy", "Partly Cloudy / Windy", "Light Rain with Thunder", "Thunder",  "Thunder / Windy", "Fair / Windy", "Mostly Cloudy / Windy", "Scattered Clouds")
heavey_condition = c("Heavy T-Storm", "Heavy T-Storm / Windy", "Heavy Rain / Windy", "Thunderstorms and Rain", "Heavy Rain", "T-Storm", "Thunder in the Vicinity", "T-Storm / Windy", "Thunderstorm", "Ice Pellets", "Thunder and Hail", "Wintry Mix", "Snow")
median_condition = c("Rain", "Rain / Windy", "Rain and Sleet")
fog_condition = c("Fog", "Patches of Fog", "Light Freezing Fog", "Haze", "Smoke")
nc_data$Weather_Condition = sapply(as.vector(nc_data$Weather_Condition), function(x) if(x %in% light_condition) "light_condition" else x )
nc_data$Weather_Condition = sapply(as.vector(nc_data$Weather_Condition), function(x) if(x %in% heavey_condition) "heavy_condition" else x )
nc_data$Weather_Condition = sapply(as.vector(nc_data$Weather_Condition), function(x) if(x %in% median_condition) "median_condition" else x )
nc_data$Weather_Condition = sapply(as.vector(nc_data$Weather_Condition), function(x) if(x %in% fog_condition) "fog_condition" else x )
nc_data$Weather_Condition = sapply(as.vector(nc_data$Weather_Condition), function(x) if(x %in% c("")) "N/A" else x )
unique(nc_data$Weather_Condition)
```

```{r}
write.csv(nc_data,'nc_new.csv')
```

```{r}
nc_new <- read.csv('nc_new.csv')
```

```{r}
nc_new <- nc_new[3:32]
```

```{r}
nc_new <- nc_new %>% filter(Wind_Direction != 'N/A') %>% filter(Weather_Condition != 'N/A')
```

```{r}
str(nc_new)
```

## 1D Marginal Distribution
## Temperature
```{r}
library(ggplot2)
```

```{r}
ggplot(nc_new, aes(x=Temperature.F., fill="#FF6666")) +
  geom_histogram(color="white",alpha=0.7) +
  labs(title="Histogram of Temperature") +
  theme(legend.position="none", plot.title=element_text(hjust=0.5))
```

## Wind_Chill
```{r}
ggplot(nc_new, aes(x=Wind_Chill.F.)) +
  geom_histogram(color="white",alpha=0.7, fill="darkblue") +
  labs(title="Histogram of Wind_Chill") +
  theme(legend.position="none", plot.title=element_text(hjust=0.5))
```

## Humidity
```{r}
ggplot(nc_new, aes(x=Humidity...)) +
  geom_histogram(color="white",alpha=0.7, fill="darkgreen") +
  labs(title="Histogram of Humidity") +
  theme(legend.position="none", plot.title=element_text(hjust=0.5))
```

## Pressure
```{r}
ggplot(nc_new, aes(x=log(Pressure.in.))) +
  geom_histogram(color="white",alpha=0.7, fill="orange") +
  labs(title="Histogram of Pressure") +
  theme(legend.position="none", plot.title=element_text(hjust=0.5))
```

## Visibility
```{r}
ggplot(nc_new, aes(x=Visibility.mi.)) +
  geom_histogram(color="white",alpha=0.7, fill="#56B4E9") +
  labs(title="Histogram of Visibility") +
  theme(legend.position="none", plot.title=element_text(hjust=0.5))
```

## Wind_Direction
```{r}
ggplot(data = nc_new, aes(x = factor(Wind_Direction), fill = factor(Wind_Direction))) +
  geom_bar() +
  ggtitle("Wind Direction") +
  theme(axis.text.x = element_text(angle = 60, hjust = 1, size = 7)) +
  guides(fill=FALSE)+
  xlab("Wind Direction") 
```

## Wind_Speed
```{r}
ggplot(nc_new, aes(x=log(Wind_Speed.mph.))) +
  geom_histogram(color="white",alpha=0.7, fill="pink") +
  labs(title="Histogram of Wind Speed") +
  theme(legend.position="none", plot.title=element_text(hjust=0.5))
```

## No Exit
```{r}
ggplot(data = nc_new, aes(x = factor(No_Exit), fill = factor(No_Exit))) +
  geom_bar(width = 0.4) +
  ggtitle("No Exit") +
  theme(axis.text.x = element_text(angle = 60, hjust = 1, size = 7)) +
  guides(fill=FALSE)+
  xlab("No Exit")  
```

## 2D Correlation Plot
## Temperature 
```{r}
ggplot(data = nc_new, aes(x=Temperature.F., y = Severity, color = Severity)) +
  geom_point() +
  geom_smooth(methon = lm, color = 'red', level = 0.95, se = FALSE)+
  xlab("Temperature") +
  ylab("Severity") +
  ggtitle("Severity VS Temperature")
```

## Wind Chill 
```{r}
ggplot(data = nc_new, aes(x=factor(Severity), y = nc_new$Wind_Chill.F., fill = factor(Severity))) +
  geom_boxplot() +
  xlab("Severity") +
  ylab("Wind Chill") +
  ggtitle("Severity VS Wind Chill")
```

## Humidity
```{r}
ggplot(data = nc_new, aes(x = factor(Severity), y=nc_new$Humidity..., fill = factor(Severity))) +
  geom_boxplot() +
  xlab("Severity") +
  ylab("Humidity") +
  ggtitle("Severity VS Humidity")
```

## Pressure 
```{r}
ggplot(data = nc_new, aes(y=log(Pressure.in.), x = factor(Severity), fill = factor(Severity))) +
  geom_boxplot() +
  xlab("Severity") +
  ylab("Pressure") +
  ggtitle("Severity VS Pressure")
```

## Visibility
```{r}
ggplot(data = nc_new, aes(x=nc_new$Visibility.mi., y = Severity, color = Severity)) +
  geom_point() +
  geom_smooth()+
  xlab("Visibility") +
  ylab("Severity") +
  ggtitle("Severity VS Visibility")
```

## Wind Direction
```{r}
library(vcd)
mosaic(Severity ~ Wind_Direction, data = nc_new)
```

## Wind Speed
```{r}
ggplot(data = nc_new, aes(y=log(Wind_Speed.mph.), x = factor(Severity), fill = factor(Severity))) +
  geom_boxplot() +
  xlab("Severity") +
  ylab("Wind Speed") +
  ggtitle("Severity VS Wind Speed")
```

## No Exit
```{r}
mosaic(Severity ~ No_Exit, data = nc_new)
```

```{r}
noexit = nc_new$No_Exit
as.data.frame(sort(table(noexit),decreasing = TRUE))
```





















